### ISSUE TITLE
1.8.0: build fails

### ISSUE THREAD

**Issue by kloczek** [DentonW/DevIL#94]
gcc 11 from Fedora rawhide
```console
[  1%] Building CXX object src-IL/CMakeFiles/IL.dir/src/il_jp2.cpp.o
cd /home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/x86_64-redhat-linux-gnu/src-IL && /usr/bin/g++ -DIL_EXPORTS -I/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/include -I/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/../include -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -DNDEBUG -fPIC -o CMakeFiles/IL.dir/src/il_jp2.cpp.o -c /home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp: In function ‘int iJp2_file_read(jas_stream_obj_t*, char*, int)’:
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp:319:9: warning: statement has no effect [-Wunused-value]
  319 |         obj;
      |         ^~~
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp: In function ‘int iJp2_file_write(jas_stream_obj_t*, char*, int)’:
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp:325:9: warning: statement has no effect [-Wunused-value]
  325 |         obj;
      |         ^~~
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp: In function ‘long int iJp2_file_seek(jas_stream_obj_t*, long int, int)’:
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp:331:9: warning: statement has no effect [-Wunused-value]
  331 |         obj;
      |         ^~~
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp: In function ‘int iJp2_file_close(jas_stream_obj_t*)’:
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp:348:9: warning: statement has no effect [-Wunused-value]
  348 |         obj;
      |         ^~~
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp: At global scope:
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp:353:9: error: invalid conversion from ‘int (*)(jas_stream_obj_t*, char*, int)’ {aka ‘int (*)(void*, char*, int)’} to ‘int (*)(jas_stream_obj_t*, char*, unsigned int)’ {aka ‘int (*)(void*, char*, unsigned int)’} [-fpermissive]
  353 |         iJp2_file_read,
      |         ^~~~~~~~~~~~~~
      |         |
      |         int (*)(jas_stream_obj_t*, char*, int) {aka int (*)(void*, char*, int)}
/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/src-IL/src/il_jp2.cpp:354:9: error: invalid conversion from ‘int (*)(jas_stream_obj_t*, char*, int)’ {aka ‘int (*)(void*, char*, int)’} to ‘int (*)(jas_stream_obj_t*, const char*, unsigned int)’ {aka ‘int (*)(void*, const char*, unsigned int)’} [-fpermissive]
  354 |         iJp2_file_write,
      |         ^~~~~~~~~~~~~~~
      |         |
      |         int (*)(jas_stream_obj_t*, char*, int) {aka int (*)(void*, char*, int)}
make[2]: *** [src-IL/CMakeFiles/IL.dir/build.make:514: src-IL/CMakeFiles/IL.dir/src/il_jp2.cpp.o] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/DevIL-1.8.0/DevIL/x86_64-redhat-linux-gnu'
```

**Comment by kloczek** [comment]
I've been trying build with patches added after v1.8.0 tag but result is the same.

**Comment by DentonW** [comment]
Merged pull request #91

**Comment by kloczek** [comment]
Q: do you have maybe some plans to make new release? (1.8.1?)🤔
